bet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^coupon/', include('coupon.urls', namespace='coupon')),
    url(r'^games/', include('games.urls', namespace='games')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('games/', include('games.urls', namespace='games')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.conf.urls import url
from games import views
from django.urls import path
from django.views.generic import edit

app_name = 'games'
urlpatterns = [
    url(r'^$', views.GameCreate.as_view(), name='games'),
    url(r'^games_list/$', views.GamesList.as_view(), name='games_list'),
    url(r'^games_detail/(?P<pk>\d+)/$', views.GamesDetail.as_view(), name='games_detail'),
              ]

games/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import render, redirect
from django.utils.translation import ugettext as _
from django.utils import timezone


class Games(models.Model):
    games_tour = models.IntegerField("Tour", primary_key=True, unique=True, null=False, default='0')
    games_match1 = models.CharField("Match 1", max_length=50)
    games_match2 = models.CharField("Match 2", max_length=50)
    games_match3 = models.CharField("Match 3", max_length=50)
    date_time = models.DateTimeField(auto_now_add=True)


   
    def __str__(self):
        return "Games tour nmr: {}".format(self.pk)

    def get_absolute_url(self):
        """
        Handy way of getting the url of the object to its detail view page
        """
        return reverse('games')        


    class Meta:
        verbose_name_plural = 'Games'

games/forms.py
from django.contrib import admin
from django.forms import (ModelForm, ValidationError, CharField)
from games.models import Games
from django import forms
from django.utils.translation import ugettext_lazy as _


class GamesForm(ModelForm):
    class Meta:
        model = Games
        fields = (
            'games_tour',
            'games_match1',
            'games_match2',
            'games_match3',

        )

games/views.py
from coupon.models import Coupon, Games
from django.views import generic
from games.forms import GamesForm
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from games.models import Games
from django.contrib.auth.mixins import UserPassesTestMixin


#Only admins should be able to create games
class GameCreate(UserPassesTestMixin, generic.CreateView):
    form_class = GamesForm   
    template_name = 'games/games_form.html'

    #With this test we check that is the user is admin, can be modified to add more contraints.
    #We can use this method to check stuff in other views, straightforward and easy.
    def test_func(self):
        return self.request.user.is_superuser


#All the games and results are available even without login:

class GamesList(generic.ListView):
    #You can specify template name or default in this case games_list.html will be used
    template_name = 'games/show_games.html'

    def get(self, request, *args, **kwargs):
        return super(GamesList, self).get(request, *args, **kwargs)
        
    def get_queryset(self):
        return Games.objects.all()

class GamesDetail(generic.DetailView):
    model = Games

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(GamesDetail, self).get(request, *args, **kwargs)

    def get_coupon_tour(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.object.pk
    
    def get_context_data(self, **kwargs):
        context = super(GamesDetail, self).get_context_data(**kwargs)
        #set some more context below.
        self.object = self.get_object()
        qs = Coupon.objects.filter(coupon_tour=self.object.pk).values()
        context = {
            'coupon': qs,
            'object': self.object,
        }
        return context

games/templates/games/games_coupons.html
{% for object in object_list %}
{{ object }}
{% endfor %}

games/templates/games/games_detail.html
 {% block main %}    
  <div class="col-sm-6 content-boxes-v3">
      <div class="clearfix margin-bottom-30">
        <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-pointer"></i>
        <div class="content-boxes-in-v3">
          <p>Tour</p>
          <h2 class="heading-sm">{{ object.pk }}</h2>
          <p>{{ object.games_match1 }}</p>
          <p>{{ object.games_match2 }}</p>
          <p>{{ object.games_match3 }}</p>
        </div>
      </div>
  </div>

  {% if coupon %}
    <div class="col-lg-12">
      <div class="col-lg-12">
        <h1>Games</h1>
        <p class="lead">Below is the list of games</p>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Coupon</th>
              <th>Bet 1</th>
              <th>Bet 2</th>
              <th>Bet 3</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            {% for object in coupon %}
            <tr>
              <td><i class="icon-custom icon-sm rounded-x icon-bg-u icon-line icon-directions"></i></td>
              <td data-label="Coupon pk">{{ object.pk }}</td>
              <td data-label="bet1">{{ object.bet1 }}</td>
              <td data-label="bet2">{{ object.bet2 }}</td>
              <td data-label="bet3">{{ object.bet3 }}</td>
              <td data-label="Amount">{{ object.coupon_amount }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
    <p>No bets placed yet.</p>
  {% endif %}
{% endblock %}

games/templates/games/games_form.html
<form method="post">
    {% csrf_token %}
    {% for item in form %}
    <p>{{ item.label }}</p>
    <p>{{ item }}</p>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

games/templates/games/show_games.html
{% block title %}
    <title>Games List</title>
{% endblock %}

{% block main %}
<!-- Page Content -->
<div class="container">
    <div class="row">
      
      {% if object_list %}
        <div class="col-lg-12">
            <h1>Games</h1>
            <p class="lead">Below is the list of games</p>
            <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Tour</th>
                <th>Date & Time</th>
              </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td><i class="icon-custom icon-sm rounded-x icon-bg-u icon-line icon-directions"></i></td>
                <td data-label="Tour"><a href="{% url 'games:games_detail' object.pk %}">{{ object.pk }}</a></td>
                <td data-label="Date & Time"><strong>{{ object.date_time}}</strong></td>
            
           </tr>
            {% endfor %}
            {% endif %}

        </tbody>
        </table>
        </div>        
    </div>
</div>
{% endblock %}