bet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^coupon/', include('coupon.urls', namespace='coupon')),
    url(r'^games/', include('games.urls', namespace='games')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('games/', include('games.urls', namespace='games')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.conf.urls import url
from games import views
from django.urls import path
from django.views.generic import edit

app_name = 'games'
urlpatterns = [
    url(r'^$', views.GameCreate.as_view(), name='games'),
    url(r'^games_list/$', views.GamesList.as_view(), name='games_list'),
    url(r'^games_detail/(?P<pk>\d+)/$', views.GamesDetail.as_view(), name='games_detail'),
              ]

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
      {% block title %}
          <title>210</title>
      {% endblock %}

      {% block head %}
          {% include "head.html" %}
      {% endblock %}
  </head>

  <body class="top-navigation pace-done animated fadeInRight">
    <div id="wrapper">
            <div id="page-wrapper" class="gray-bg">
            {% block header %}
                {% include "header.html" %}
            {% endblock %}
            {% block main %}
            <p>This is the base template.</p>
            {% endblock %}

            {% block footer %}
                {% include "footer.html" %}
            {% endblock %}
            </div>
            {% block foot %}
                {% include "foot.html" %}
            {% endblock %}
  </body>
</html>

templates/foot.html
{% load staticfiles %}
<!-- Core JS -->
<!-- Here you can load the javascripts like the example 
<script type="text/javascript" src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script> -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

templates/footer.html
{% block footer %}
<div class="footer">
    <div class="col-lg-12">
        Copyright 210 Company © 2014-2018
        <div class="pull-right">
            The next betting round starts in: Django_function_here? or something else...
        </div>
    </div>
</div>
{% endblock %}

templates/head.html
{% load staticfiles %}
<!-- Meta 
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/iCheck/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}" >




<!-- Web Fonts -->
<!-- <link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>-->

templates/header.html
{% load staticfiles %}
<div class=" col-lg-12">
    <div class="row border-bottom white-bg">
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a href="#" class="navbar-brand">2 1 0</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a aria-expanded="false" role="button" href="{% url 'games:games_list' %}"> Games Results</a>
                    </li>
                    <li class="">
                        <a aria-expanded="false" role="button" href="{% url 'login' %}"> Register yourself</a>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Bet on the next gane <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="">Game number: 210</a></li>
                            <li><a href="">Menu item 2</a></li>
                            <li><a href="">Menu item 3</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Other Menu item <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="">Menu item 1 </a></li>
                            <li><a href="">Menu item 2 </a></li>
                            <li><a href="">Menu item 3 </a></li>
                            <li><a href="">Menu item 4 </a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li >
                            <a href="{% url 'login' %}">
                                <i class="fa fa-sign-in"></i> Login
                            </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>